image: golang:1.8.1-alpine

clone:
  depth: 1

options:
  docker: true

pipelines:

  default:
    - step:
        script:
          - apk add --no-cache bash curl
          - chmod +x build.sh && ./build.sh

  tags:
    "**":
      - step:
          script:
            - apk add --no-cache bash curl
            - chmod +x build.sh && ./build.sh
